version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: poke-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pokedex
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: retro-poke-redis
    ports:
      - "6380:6379"
    volumes:
      - retro_redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  mongodb_data:
  retro_redis_data:
